leapdao/leap-core

package.json

This removes "License should be a valid SPDX license expression" npm warning

use proper SPDX license code.

---

lib/outpoint.js

`Outpoint` has a function `isOutpoint`. It uses `instanceof` to check whether the parameter is an `Outpoint`. 
In `Input`'s `constructor` `isOutpoint` is used to check if the `options` are indeed an `Outpoint`.
This lead to a really hard to find bug for me in the burner wallet. Here's why:
We're inserting the leap-core web3 provider through dapperatus into the burner wallet. However, we're NOT doing transactions within dapparatus. These are done (due to the burner wallet's design 🤷‍♂️) in the burner wallet itself.
This leads us to import "leap-core" for its `helpers` in the burner wallet while our web3 object comes from dapparatus. When we want to send a transaction now, we'll get `getUnspent` from `dapparatus.web3`, while our helpers are from `burner-wallet.helpers`. Subsequently, when …

Replace instanceof usage with duck-typing

---

lib/helpers.js

`getUnspent` JSON RPC supports 2 arguments. With current implementation it is not possible (?) to specify color.
Reference: https://github.com/leapdao/leap-node/blob/master/src/api/methods/getUnspent.js#L3
This is BREAKING CHANGE, old API calls will need to be changed to provide color as well.

[💥breaking] fix: make getUnspent require 2 params (address and color)

---

lib/exit.js
lib/helpers.js

I had a problem in the burner wallet with exits that were not sunDai. `fastSellAmount` would always throw `Error: Failed to subscribe to new newBlockHeaders to confirm the transaction receipts.`.
To circumvent this behavior, I'm using the base JSON-RPC call that doesn't call "newBlockHeaders".
I'm using this fix in https://github.com/leapdao/burner-wallet/pull/71

Query for inclusion of tx to market maker

---

index.d.ts
lib/helpers.js

- got rid of `async/await` 
- supporting Ethers.js. Detect if provided plasma object is Web3 or JSONRPCProvider of Ethers.
- added `sendSignedTransaction` to typedefs. Without a proper return type for now — need to add Ethers.js typedefs for that
- use proper timeout-loop: the previous one did nothing for async code
Resolves #108 
Veried for Ethers here: https://github.com/leapdao/leap-guardian/pull/12
Haven't verified for Web3 yet

fix: rectify sendSignedTransaction

---

index.d.ts
lib/exit.js
lib/helpers.js

- add a getUnspentByAddress RCP helper. After the #68, there is no helper to get unspents of all the colors for a given address.
This feature is used in Bridge UI.
- fix typedef for getUnspent
- make `getUnspent` helper to delegate to `getUnspentForAddress` or `getUnspentForAddressColor` depending on the number of parameters provided. This makes it backward compatible with pre-#68 code

feat: add getUnspentByAddress RPC helper and fix typedefs

---

lib/outpoint.js
lib/outpoint.spec.js

Outpoint.hash is always Buffer, so should be compared with `equals`, not `===`.

fix: proper Outpoint comparison

---

lib/transaction.js
lib/transaction.spec.js

So that we can use Tx helpers like `transferFromUtxos` to create NST transfers as well.
Requires #124

feat: copy token data for NSTs in calcOutputs

---

lib/constants.js
lib/transaction.js
lib/transaction.spec.js

Moving common code to "optimistically presume" `to`/`from`/`value` of the transaction  from [leap-node](https://github.com/leapdao/leap-node/blob/5dc77eda64dd3949a88b95a511fc0ab931e841b5/src/api/methods/txResponse.js).
Intended to work for "standard" transactions under assumptions:
- one tx — one signer (all the inputs are from the same account)
- one tx — one beneficiary/destination (first output)

feat: add to/from/value getters to Transaction class

---

index.d.ts
lib/helpers.js
lib/helpers.spec.js
lib/period.js

- added `plasma_getPeriodByBlockHeight` JSON RPC extension ([docs](https://github.com/leapdao/leapdao-docs/pull/39))
- improved `getProof` helper so it fetches period data automatically:
```ts
helpers.getProof(plasma: ExtendedWeb3 | LeapEthers, tx: LeapTransaction)
```
Resolves #115

feat: add CAS support for helpers.getProof

---

index.d.ts
lib/helpers.js

- deprecates getUnspentAll and getUnspentByAddress #139
- allow to get all utxos by color with `getUnspent(null, 1)` #137 
- drop LeapEthers in favour of LeapProvider https://github.com/leapdao/leap-provider/pull/3

Fix: better getUnspent

---

lib/output.js
lib/transaction.js

Otherwise it is `undefined` and `calcInputs` can lead to wrong results

fix: set default color for Output and calcInput to 0

---

lib/transaction.js
lib/transaction.spec.js

Adds a half-assed option to limit an amount of inputs produced by `calcInputs`.
Requires https://github.com/leapdao/leap-core/pull/148

feat: allow to cap number of inputs for calcInputs

---

lib/helpers.js

Resolves #144 
preserves backward compatibility with just `getColor()`.
Overall, all the three cases should be supported:
```
// erc20
plasma.getColor()
// erc721
plasma.getColor(true)
// erc1948
plasma.getColor(false, true)
```

fix: getColors should accept two optional params

---

package.json

- BREAKING CHANGE: `getColors()` RPC helper now returns all the colors instead of only erc20 (#145)
- `getColors` RPC helper now supports ERC721 and ERC1948 (#145):
```
// erc20 + erc721 + erc1948
plasma.getColors()
// erc721
plasma.getColors('erc20')
// erc721
plasma.getColors('erc721')
// erc1948
plasma.getColors('erc1948')
```

Release 0.36.0

---

lib/period.js
lib/period.spec.js

Reason: wrong check (blockPos is undefined, not negative)

fix: Period.proof throwing incorrect error when tx is not in the period.

---

index.d.ts
lib/exit.js
package.json
yarn.lock

This way the client has a chance to store the transfer tx, to resume exit process later e.g.
if the user rejected exit signature.

feat(exit): emit signed exit transfer tx details before signing an exit message

---

index.d.ts
lib/helpers.js
lib/helpers.spec.js
lib/period.js
lib/period.spec.js

Suggestion for #166 
1. Set `usePrev` by default. BREAKING change
2. Accept optional third arguments of `PeriodOptions` type:
allows to set validator data and set `usePrev` to false for legacy proofs.

chore: rework Period object constructor

---

index.d.ts
lib/helpers.js
lib/helpers.spec.js
lib/period.js
lib/period.spec.js

Resolves: https://github.com/leapdao/leap-core/issues/165

feat: add previous period hash to proofs and roots if present

---

.github/workflows/main.yml
.travis.yml

- Using Github Actions instead of Travis.
- Uploads coverage to codecov.io (wasn't uploaded with Travis)
Reason for Github Actions:
- native, no need to open external site
- once adopted, allow extra automations (e.g. greeting contributors etc)

chore(ci): add tests and coverage via Github Actions

---

index.d.ts
lib/helpers.spec.js
lib/period.js
lib/period.spec.js

getPeriodByBlockHeight API returns `validatorAddress`, not `ownerAddress`:
```
curl --location --request POST 'https://testnet-node.leapdao.org/' \
--header 'Content-Type: application/json' \
--data-raw '{
"method": "plasma_getPeriodByBlockHeight",
"params": ["190000"],
"id": 1,
"jsonrpc": "2.0"
}'
```
returns
```
{
"jsonrpc": "2.0",
"id": 1,
"result": [
{
"periodStart": 189984,
"periodEnd": 190015,
"casBitmap": "0xc000000000000000000000000000000000000000000000000000000000000000",
"slotId": "0",
"validatorAddress": "0xDe42468b9ba193384eA76e337BAe1676932133Cf"
}
]
}
```

fix(period): wrong name for validator address attribute in period options

---

lib/helpers.js
lib/helpers.spec.js

Adapts to the changes introduced in https://github.com/leapdao/leap-node/pull/403/
getPeriodByBlockHeight API now returns _object_ instead of _array_.
This is BREAKING CHANGE

feat(period): adapt to new getPeriodByBlockHeight API

---

.babelrc
.eslintrc
index.d.ts
lib/exit.js
lib/helpers.spec.js
lib/output.js
lib/output.spec.js
lib/transaction.js
lib/transaction.spec.js
lib/util.js
lib/util.spec.js
package.json
yarn.lock

- replaced all the JSBI/jsbi-utils arithmetics with native code (see https://github.com/GoogleChromeLabs/jsbi for mappings)
- using literals. `BigInt(12)` → `12n`
Native BigInts arent' serializable to JSON (it is up to clients to implement this).
Added [Utils.toJSON](https://github.com/leapdao/leap-core/compare/feat/native-bigint?expand=1#diff-3deb3f32958bb937ae05c6f3e4abbdf5R204) / [Utils.fromJSON](https://github.com/leapdao/leap-core/compare/feat/native-bigint?expand=1#diff-3deb3f32958bb937ae05c6f3e4abbdf5R195) to handle arbitrary objects serialization/deserialization. These objects may include BigInt. Caveat: regular `JSON.parse` or `require` won't read BigInt value produced by `Utils.toJSON` — you have to use `Utils.fromJSON` to deserialize.
- added `@babel/plugin-syntax-bigint` to …

feat: use native BigInt instead of JSBI
