leapdao/leap-core

lib/block.js, lib/block.spec.js, lib/period.js, lib/period.spec.js
=> Remove block signing, add prevHash to Period constructor

lib/block.js, lib/block.spec.js, lib/encoding.js, lib/merkleTree.js, lib/outpoint.js, lib/outpoint.spec.js, lib/output.js, lib/output.spec.js, lib/period.js, lib/period.spec.js, lib/transaction.js, lib/transaction.spec.js, lib/util.js
- added color to outputs as 2 bytes value.
- fixed all tests in lib.
=> added color to outputs

lib/helpers.spec.js
=> added polyfill to fix tests

index.d.ts, lib/transaction.js, lib/transaction.spec.js, lib/type.js
We need `signerAddr` field for a slot selection algo
=> Extend validatorJoin and validatorLogout txs, drop validatorLeave

lib/helpers.js
For https://github.com/parsec-labs/parsec-node/pull/55
=> Inject parsec_status method into web3

lib/output.js, lib/output.spec.js
=> Throw if color out of range

lib/input.js, lib/input.spec.js, lib/output.js, lib/output.spec.js, lib/transaction.js, lib/transaction.spec.js, lib/type.js
- add SPEND_COND type
- add sigHash for SPEND_COND
- allow to add msgData later
=> add SPEND_COND tx type

.eslintrc, .eslintrc.js, .travis.yml, lib/exit.js, lib/exit.spec.js, package-lock.json, package.json, yarn.lock
=> add travis config

index.d.ts, lib/block.js, lib/constants.js, lib/helpers.js, lib/helpers.spec.js, lib/period.js, lib/period.spec.js, lib/util.js, package-lock.json, package.json, yarn.lock
- find period block range
- find youngest input in tx
- generate period inclusion proof for tx
=> add more helpers

lib/output.js, lib/output.spec.js
Affecting: https://github.com/leapdao/leap-node/issues/128
=> fix: broken serialization for large outputs

lib/transaction.js, lib/transaction.spec.js, yarn.lock
Fixes https://github.com/leapdao/leap-core/issues/35
=> Fix consolidate construction

lib/transaction.js, lib/transaction.spec.js, yarn.lock
Addresses https://github.com/leapdao/leap-core/issues/34
=> Tx constructor

lib/exit.spec.js, lib/helpers.js, lib/period.js, lib/period.spec.js
Resolves https://github.com/leapdao/leap-core/issues/50
=> extensible proof structure

index.d.ts, lib/exit.js, lib/helpers.js, lib/helpers.spec.js, lib/output.js, lib/output.spec.js, lib/transaction.spec.js, lib/util.js, package.json, yarn.lock
Follow up for #54
connected #48
=> More JSBI/BigInt

lib/output.js, lib/output.spec.js
resolves https://github.com/leapdao/leap-node/issues/145
=> disallow outputs with negative or 0 value

lib/helpers.js, lib/helpers.spec.js, lib/period.js
e.g. blocknum 32, 64 etc
Related issue: leapdao/bridge-ui#123
=> fix: periodBlockRange didn't work correct for period boundaries 

lib/block.js, lib/transaction.js, package.json, yarn.lock
why compare javascript objects 🤷‍♂️
=> remove fast equal lib

index.d.ts, lib/input.js, lib/input.spec.js, lib/transaction.js, lib/transaction.spec.js, lib/type.js
as we need signed consolidates now
=> 🔪 get rid of CONSOLIDATE tx in favour of TRANSFER

index.d.ts
Required for https://github.com/leapdao/bridge-ui/issues/128
=> add delays to NodeConfig typedef

lib/transaction.js, test/helpers/web3.js
`eth_sign` not implemented in status provider
=> Temporary use personal.sign for web3 signing

index.d.ts, lib/helpers.js
Required for https://github.com/leapdao/leap-node/pull/174 to be useable
=> add getUnspentAll JSON RPC method

index.d.ts
Related to https://github.com/leapdao/bridge-ui/issues/188
=> add rootNetworkId to NodeConfig

lib/period.js
Blocked by https://github.com/leapdao/leap-node/issues/236
=> feat: getProof to support Ethers

lib/block.spec.js, lib/output.js, lib/output.spec.js, lib/util.js
=> Add support for NSTs

index.d.ts, lib/exit.js, package.json, yarn.lock
Part of https://github.com/leapdao/burner-wallet/issues/4
TODO:
=> feat: helper for submitting fast exits

lib/transaction.js
=> fix(tx): correct sig check in hashBuf

lib/transaction.js, lib/transaction.spec.js
=> fix(tx): allow to serialize unsigned transfer tx

lib/exit.js
=> fix: closing bracket in a wrong place

lib/transaction.js
resolves https://github.com/leapdao/leap-core/issues/11 and needed for https://github.com/leapdao/leap-node/pull/291
=> allow to sign selective inputs

lib/period.js, lib/period.spec.js
needed for https://github.com/leapdao/leap-contracts/issues/211
=> add cas bitmap to validator data

lib/helpers.js, lib/period.js, lib/transaction.js
- move `periodBlockRange` from helpers to Period (so Period doesn't depend on helpers)
- move `calcInputs` and `calcOutputs` from helpers to Transaction (so Transaction doesn't depend on helpers)
=> refactor: breaking dependency graph cycle

index.d.ts, lib/helpers.js, lib/helpers.spec.js
=> consolidateUTXOs helper

lib/transaction.js, lib/transaction.spec.js
Fixes incorrect serialization introduced in #127
=> fix: serialize tx value as a decimal string

lib/period.spec.js
in an attempt to debug integration test failures
=> test period proof without CAS

lib/helpers.js
=> fix: getUnspent(0xada) returns only for color 0

index.d.ts, lib/helpers.js, lib/helpers.spec.js
Should be helpful to solve problems like https://github.com/leapdao/bridge-ui/issues/253
=> feat: allow to specify period data fallback for getProof helper

lib/output.js, lib/output.spec.js
resolves current testnet blocker
=> allow NFTs with 0 id
